### ISSUE TITLE
Move getFileLocation function to CMakeBuilder class

### ISSUE THREAD

**Issue by lingyuncai** [intel/webinizer#35]
Currently, the [getFileLocation](https://github.com/intel/webinizer/blob/f6c375223d2e80fff7e6bd8191fb0d2871ef31ef/src/actions/file_change.ts#L17-L42) function is used by [CMakeBuilder](https://github.com/intel/webinizer/blob/f6c375223d2e80fff7e6bd8191fb0d2871ef31ef/src/builders/cmake.ts#L60) only and the logic was implemented for cmake errors logs as well. We should probably move it to the `CMakeBuilder` class, and implement separate methods for other builders if needed in the future.

**Comment by sinapy** [comment]
could you give some examples for testing? @lingyuncai

**Comment by lingyuncai** [comment]
Hi @sinapy, I changed this issue slightly as this is more suitable for `good first issue`. If you are still interested, please feel free to submit a PR :)

**Comment by lingyuncai** [comment]
Close as fixed in #39.
